backend:
  name: git-gateway
  branch: main 
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
  - name: "pages"
    label: "Sidkonfiguration"
    delete: true
    editor:
      preview: false
    files:
      - name: "news"
        label: "Senaste nytt"
        file: "site/content/news.yml"
        fields:
          - label: Nyhet
            name: items
            widget: list
            fields:
              - {label: date, name: date, widget: date}
              - {label: Rubrik, name: text, widget: string}
              - {label: "Länktext", name: text, widget: string}
              - {label: "Länk", name: url, widget: string}
